from __future__ import annotations

UNIVERSE_BY_MARKET: dict[str, dict[str, str]] = {
    "KR": {
        "005930.KS": "Samsung Electronics",
        "000660.KS": "SK hynix",
        "035420.KS": "NAVER",
        "051910.KS": "LG Chem",
        "005380.KS": "Hyundai Motor",
        "012330.KS": "Hyundai Mobis",
        "068270.KS": "Celltrion",
        "105560.KS": "KB Financial Group",
        "055550.KS": "Shinhan Financial Group",
        "034730.KS": "SK Inc.",
        "003670.KS": "POSCO Holdings",
        "017670.KS": "SK Telecom",
        "247540.KQ": "EcoPro BM",
        "086520.KQ": "Ecopro",
        "091990.KQ": "Celltrion Healthcare",
        "196170.KQ": "Alteogen",
        "066970.KQ": "L&F",
        "140860.KQ": "Park Systems",
        "263750.KQ": "Pearl Abyss",
        "293490.KQ": "Kakao Games",
        "278280.KQ": "Chunbo",
        "058470.KQ": "Leeno Industrial",
        "214150.KQ": "Classys",
        "357780.KQ": "Soulbrain",
    },
    "US": {
        "AAPL": "Apple",
        "MSFT": "Microsoft",
        "NVDA": "NVIDIA",
        "AMZN": "Amazon",
        "GOOGL": "Alphabet",
        "META": "Meta Platforms",
        "TSLA": "Tesla",
        "BRK-B": "Berkshire Hathaway",
        "JPM": "JPMorgan Chase",
        "LLY": "Eli Lilly",
        "AVGO": "Broadcom",
        "NFLX": "Netflix",
        "AMD": "Advanced Micro Devices",
        "PLTR": "Palantir",
        "COST": "Costco Wholesale",
        "SPY": "SPDR S&P 500 ETF Trust",
        "QQQ": "Invesco QQQ Trust",
    },
}
